In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/job-classification-dataset/jobclassinfo2.csv


In [2]:
df = pd.read_csv('../input/job-classification-dataset/jobclassinfo2.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   ID                    66 non-null     int64 
 1   JobFamily             66 non-null     int64 
 2   JobFamilyDescription  66 non-null     object
 3   JobClass              66 non-null     int64 
 4   JobClassDescription   66 non-null     object
 5   PayGrade              66 non-null     int64 
 6   EducationLevel        66 non-null     int64 
 7   Experience            66 non-null     int64 
 8   OrgImpact             66 non-null     int64 
 9   ProblemSolving        66 non-null     int64 
 10  Supervision           66 non-null     int64 
 11  ContactLevel          66 non-null     int64 
 12  FinancialBudget       66 non-null     int64 
 13  PG                    66 non-null     object
dtypes: int64(11), object(3)
memory usage: 7.3+ KB


In [3]:
df.head(3)

ID  JobFamily    JobFamilyDescription  JobClass JobClassDescription  \
0   1          1  Accounting And Finance         1        Accountant I   
1   2          1  Accounting And Finance         2       Accountant II   
2   3          1  Accounting And Finance         3      Accountant III   

   PayGrade  EducationLevel  Experience  OrgImpact  ProblemSolving  \
0         5               3           1          3               3   
1         6               4           1          5               4   
2         8               4           2          6               5   

   Supervision  ContactLevel  FinancialBudget    PG  
0            4             3                5  PG05  
1            5             7                7  PG06  
2            6             7               10  PG08

In [4]:
df.isnull().sum()

ID                      0
JobFamily               0
JobFamilyDescription    0
JobClass                0
JobClassDescription     0
PayGrade                0
EducationLevel          0
Experience              0
OrgImpact               0
ProblemSolving          0
Supervision             0
ContactLevel            0
FinancialBudget         0
PG                      0
dtype: int64

In [5]:
object_type_features = df.select_dtypes("object").columns
object_type_features

Index(['JobFamilyDescription', 'JobClassDescription', 'PG'], dtype='object')

In [6]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

for feat_name in object_type_features: 
    df[feat_name] = le.fit_transform(df[feat_name])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    66 non-null     int64
 1   JobFamily             66 non-null     int64
 2   JobFamilyDescription  66 non-null     int64
 3   JobClass              66 non-null     int64
 4   JobClassDescription   66 non-null     int64
 5   PayGrade              66 non-null     int64
 6   EducationLevel        66 non-null     int64
 7   Experience            66 non-null     int64
 8   OrgImpact             66 non-null     int64
 9   ProblemSolving        66 non-null     int64
 10  Supervision           66 non-null     int64
 11  ContactLevel          66 non-null     int64
 12  FinancialBudget       66 non-null     int64
 13  PG                    66 non-null     int64
dtypes: int64(14)
memory usage: 7.3 KB


In [7]:
df.head()

ID  JobFamily  JobFamilyDescription  JobClass  JobClassDescription  \
0   1          1                     0         1                    0   
1   2          1                     0         2                    1   
2   3          1                     0         3                    2   
3   4          1                     0         4                    3   
4   5          2                     1         5                    4   

   PayGrade  EducationLevel  Experience  OrgImpact  ProblemSolving  \
0         5               3           1          3               3   
1         6               4           1          5               4   
2         8               4           2          6               5   
3        10               5           5          6               6   
4         1               1           0          1               1   

   Supervision  ContactLevel  FinancialBudget  PG  
0            4             3                5   4  
1            5             7                7   5  
2            6             7               10   7  
3            7             8               11   9  
4            1             1                1   0

In [8]:
X = df.drop(['PG'], axis = 1)
y = df['PG']

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)


**1)LOGISTIC REGRESSION**

In [10]:
from sklearn.linear_model import LogisticRegression
clf_lr = LogisticRegression()

clf_lr.fit(X_train, y_train)
y_pred_lr = clf_lr.predict(X_test)
print("Train Score LR-", clf_lr.score(X_train, y_train)*100 , "%")
print("Test Score LR-", clf_lr.score(X_test, y_test)*100, "%")

Train Score LR- 69.56521739130434 %
Test Score LR- 25.0 %


/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


**Confusion Matrix, Recall Score and Precision Score**

In [11]:
from sklearn.metrics import recall_score, precision_score, confusion_matrix

print("Recall score", recall_score(y_test, y_pred_lr, average='macro'))
print("Precision score", precision_score(y_test, y_pred_lr, average='macro'))
print ("CONFUSION MATRIX", confusion_matrix(y_test, y_pred_lr))

Recall score 0.26666666666666666
Precision score 0.18666666666666665
CONFUSION MATRIX [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [1 0 0 1 0 2 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 0 2 0 3]
 [0 0 0 0 0 0 0 1 0 2]]


/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**2)DECISION TREE**

In [12]:
from sklearn.tree import DecisionTreeClassifier
clf_dt = DecisionTreeClassifier()

clf_dt.fit(X_train, y_train)
y_pred_dt = clf_dt.predict(X_test)
print("Train Score LR-", clf_dt.score(X_train, y_train)*100 , "%")
print("Test Score LR-", clf_dt.score(X_test, y_test)*100, "%")

Train Score LR- 100.0 %
Test Score LR- 85.0 %


In [13]:
print("Recall score", recall_score(y_test, y_pred_dt, average='macro'))
print("Precision score", precision_score(y_test, y_pred_dt, average='macro'))
print ("CONFUSION MATRIX", confusion_matrix(y_test, y_pred_dt))

Recall score 0.73
Precision score 0.7333333333333333
CONFUSION MATRIX [[0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 1 0 0]
 [0 0 0 0 0 0 1 0 4 0]
 [0 0 0 0 0 0 0 0 0 3]]


/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Out of the two Decision Tree gives me the best result.